const Mac = [
    {
            id: 1,
            name: "iMac 24 inch M4 2024",
            image: "../../images/Logo/apple image/iMac 24 inch M4 2024.jpg",
            installment: "Trả góp 0%",
            priceOld: 39990000,
            discountPercent: 1,
            priceNew: 39600000,
        },
        {
            id: 2,
            name: "iMAC 24i 2023 M3",
            image: "../../images/Logo/apple image/iMAC 24i 2023 M3.png",
            installment: "Trả góp 0%",
            priceOld: 39990000,
            discountPercent: 1,
            priceNew: 39600000,
        },
        {
            id: 3,
            name: "Mac mini M4 2024",
            image: "../../images/Logo/apple image/Mac mini M4 2024.jpeg",
            installment: "Trả góp 0%",
            priceOld: 14990000,
            discountPercent: 5,
            priceNew: 14240500,
        },
]
const BanPhim = [
    {
            id: 1,
            name: "Logitech G Pro X TKL Lightspeed",
            image: "../../Images/BanPhim/logitech_pro_x_tkl_lightspeed.jpg",
            brand: "Logitech",
            type: "Cơ",
            switchType: "Blue Switch",
            layout: "TKL",
            connect: ["Không dây (Wireless)"],
            led: "RGB",
            priceOld: 4190000,
            discountPercent: 12,
        },
        {
            id: 2,
            name: "Corsair K70 RGB MK.2",
            image: "../../Images/BanPhim/Corsair K70 RGB MK.2.jpg",
            brand: "Corsair",
            type: "Cơ",
            switchType: "Red Switch",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 3890000,
            discountPercent: 15,
        },
        {
            id: 3,
            name: "Razer BlackWidow V4",
            image: "../../Images/BanPhim/Razer BlackWidow V4.jpg",
            brand: "Razer",
            type: "Cơ",
            switchType: "Green Switch",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 3200000,
            discountPercent: 10,
        },
        {
            id: 4,
            name: "Keychron K8 Pro",
            image: "../../Images/BanPhim/Keychron K8 Pro.jpg",
            brand: "Keychron",
            type: "Cơ",
            switchType: "Brown Switch",
            layout: "TKL",
            connect: ["Có dây", "Bluetooth"],
            led: "Đơn sắc",
            priceOld: 2590000,
            discountPercent: 5,
        },
        {
            id: 5,
            name: "Akko 3087 v2 World Tour Tokyo",
            image: "../../Images/BanPhim/Akko 3087 v2 World Tour Tokyo.jpg",
            brand: "Akko",
            type: "Cơ",
            switchType: "Red Switch",
            layout: "TKL",
            connect: ["Có dây"],
            led: "Không LED",
            priceOld: 1850000,
            discountPercent: 8,
        },
        {
            id: 6,
            name: "Logitech K120",
            image: "../../Images/BanPhim/Logitech K120.jpg",
            brand: "Logitech",
            type: "Văn phòng",
            switchType: "Khác",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "Không LED",
            priceOld: 250000,
            discountPercent: 20,
        },
        {
            id: 7,
            name: "Razer Huntsman Mini",
            image: "../../Images/BanPhim/Razer Huntsman Mini.jpg",
            brand: "Razer",
            type: "Cơ",
            switchType: "Razer Optical Red",
            layout: "60%",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 3100000,
            discountPercent: 15,
        },
        {
            id: 8,
            name: "SteelSeries Apex Pro TKL",
            image: "../../Images/BanPhim/SteelSeries Apex Pro TKL.jpg",
            brand: "SteelSeries",
            type: "Cơ",
            switchType: "OmniPoint",
            layout: "TKL",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 5200000,
            discountPercent: 10,
        },
        {
            id: 9,
            name: "Corsair K100 AIR Wireless",
            image: "../../Images/BanPhim/Corsair K100 AIR Wireless.jpg",
            brand: "Corsair",
            type: "Cơ",
            switchType: "Cherry MX Ultra Low Profile",
            layout: "Full-size",
            connect: ["Không dây (Wireless)", "Bluetooth"],
            led: "RGB",
            priceOld: 7500000,
            discountPercent: 8,
        },
        {
            id: 10,
            name: "Akko 5075S Dracula Castle",
            image: "../../Images/BanPhim/Akko 5075S Dracula Castle.jpg",
            brand: "Akko",
            type: "Cơ",
            switchType: "Akko CS Switch",
            layout: "75%",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 2350000,
            discountPercent: 18,
        },
        {
            id: 11,
            name: "Logitech MX Keys S",
            image: "../../Images/BanPhim/Logitech MX Keys S.jpg",
            brand: "Logitech",
            type: "Văn phòng",
            switchType: "Khác",
            layout: "Full-size",
            connect: ["Không dây (Wireless)", "Bluetooth"],
            led: "Đơn sắc",
            priceOld: 2890000,
            discountPercent: 10,
        },
        {
            id: 12,
            name: "Keychron Q1 Pro",
            image: "../../Images/BanPhim/Keychron Q1 Pro.jpg",
            brand: "Keychron",
            type: "Cơ",
            switchType: "Brown Switch",
            layout: "75%",
            connect: ["Không dây (Wireless)", "Bluetooth"],
            led: "RGB",
            priceOld: 4990000,
            discountPercent: 12,
        },
        {
            id: 13,
            name: "DareU EK87 Queen",
            image: "../../Images/BanPhim/DareU EK87 Queen.jpg",
            brand: "DareU",
            type: "Giả cơ",
            switchType: "Khác",
            layout: "TKL",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 690000,
            discountPercent: 25,
        },
        {
            id: 14,
            name: "Razer Ornata V3",
            image: "../../Images/BanPhim/Razer Ornata V3.webp",
            brand: "Razer",
            type: "Giả cơ",
            switchType: "Razer Mecha-Membrane",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 1990000,
            discountPercent: 20,
        },
        {
            id: 15,
            name: "Fuhlen L411",
            image: "../../Images/BanPhim/Fuhlen L411.jpg",
            brand: "Fuhlen",
            type: "Văn phòng",
            switchType: "Khác",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "Không LED",
            priceOld: 220000,
            discountPercent: 15,
        },
        {
            id: 16,
            name: "Logitech G913 TKL Lightspeed",
            image: "../../Images/BanPhim/Logitech G913 TKL Lightspeed.webp",
            brand: "Logitech",
            type: "Cơ",
            switchType: "GL Tactile",
            layout: "TKL",
            connect: ["Không dây (Wireless)", "Bluetooth"],
            led: "RGB",
            priceOld: 4790000,
            discountPercent: 15,
        },
        {
            id: 17,
            name: "E-Dra EK387",
            image: "../../Images/BanPhim/E-Dra EK387.jpg",
            brand: "E-Dra",
            type: "Cơ",
            switchType: "Blue Switch",
            layout: "TKL",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 950000,
            discountPercent: 22,
        },
        {
            id: 18,
            name: "Apple Magic Keyboard",
            image: "../../Images/BanPhim/Apple Magic Keyboard.webp",
            brand: "Apple",
            type: "Văn phòng",
            switchType: "Khác",
            layout: "75%",
            connect: ["Bluetooth"],
            led: "Không LED",
            priceOld: 2790000,
            discountPercent: 5,
        },
        {
            id: 19,
            name: "Asus ROG Strix Flare II Animate",
            image: "../../Images/BanPhim/Asus ROG Strix Flare II Animate.png",
            brand: "Asus",
            type: "Cơ",
            switchType: "Red Switch",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 5490000,
            discountPercent: 10,
        },
        {
            id: 20,
            name: "HyperX Alloy Origins 60",
            image: "../../Images/BanPhim/HyperX Alloy Origins 60.webp",
            brand: "HyperX",
            type: "Cơ",
            switchType: "HyperX Red",
            layout: "60%",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 2590000,
            discountPercent: 17,
        }
]