const Mac = [
    {
            id: 1,
            name: "iMac 24 inch M4 2024",
            image: "../../images/Logo/apple image/iMac 24 inch M4 2024.jpg",
            installment: "Trả góp 0%",
            priceOld: 39990000,
            discountPercent: 1,
            priceNew: 39600000,
        },
        {
            id: 22,
            name: "Mac mini M4 pro 2024",
            image: "../../images/Logo/apple image/Mac mini M4 Pro 2024.jpg",
            installment: "Trả góp 0%",
            priceOld: 14990000,
            discountPercent: 5,
            priceNew: 14240500,
        },
        {
            id: 3,
            name: "Mac mini M4 2024",
            image: "../../images/Logo/apple image/Mac mini M4 2024.jpeg",
            installment: "Trả góp 0%",
            priceOld: 14990000,
            discountPercent: 5,
            priceNew: 14240500,
        },
]
const BanPhim = [
    {
            id: 1,
            name: "Logitech G Pro X TKL Lightspeed",
            image: "../../Images/BanPhim/logitech_pro_x_tkl_lightspeed.jpg",
            brand: "Logitech",
            type: "Cơ",
            switchType: "Blue Switch",
            layout: "TKL",
            connect: ["Không dây (Wireless)"],
            led: "RGB",
            priceOld: 4190000,
            discountPercent: 12,
        },
        {
            id: 2,
            name: "Corsair K70 RGB MK.2",
            image: "../../Images/BanPhim/Corsair K70 RGB MK.2.jpg",
            brand: "Corsair",
            type: "Cơ",
            switchType: "Red Switch",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 3890000,
            discountPercent: 15,
        },
        {
            id: 3,
            name: "Razer BlackWidow V4",
            image: "../../Images/BanPhim/Razer BlackWidow V4.jpg",
            brand: "Razer",
            type: "Cơ",
            switchType: "Green Switch",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 3200000,
            discountPercent: 10,
        },
        {
            id: 4,
            name: "Keychron K8 Pro",
            image: "../../Images/BanPhim/Keychron K8 Pro.jpg",
            brand: "Keychron",
            type: "Cơ",
            switchType: "Brown Switch",
            layout: "TKL",
            connect: ["Có dây", "Bluetooth"],
            led: "Đơn sắc",
            priceOld: 2590000,
            discountPercent: 5,
        },
        {
            id: 5,
            name: "Akko 3087 v2 World Tour Tokyo",
            image: "../../Images/BanPhim/Akko 3087 v2 World Tour Tokyo.jpg",
            brand: "Akko",
            type: "Cơ",
            switchType: "Red Switch",
            layout: "TKL",
            connect: ["Có dây"],
            led: "Không LED",
            priceOld: 1850000,
            discountPercent: 8,
        },
        {
            id: 6,
            name: "Logitech K120",
            image: "../../Images/BanPhim/Logitech K120.jpg",
            brand: "Logitech",
            type: "Văn phòng",
            switchType: "Khác",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "Không LED",
            priceOld: 250000,
            discountPercent: 20,
        },
        {
            id: 7,
            name: "Razer Huntsman Mini",
            image: "../../Images/BanPhim/Razer Huntsman Mini.jpg",
            brand: "Razer",
            type: "Cơ",
            switchType: "Razer Optical Red",
            layout: "60%",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 3100000,
            discountPercent: 15,
        },
        {
            id: 8,
            name: "SteelSeries Apex Pro TKL",
            image: "../../Images/BanPhim/SteelSeries Apex Pro TKL.jpg",
            brand: "SteelSeries",
            type: "Cơ",
            switchType: "OmniPoint",
            layout: "TKL",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 5200000,
            discountPercent: 10,
        },
        {
            id: 9,
            name: "Corsair K100 AIR Wireless",
            image: "../../Images/BanPhim/Corsair K100 AIR Wireless.jpg",
            brand: "Corsair",
            type: "Cơ",
            switchType: "Cherry MX Ultra Low Profile",
            layout: "Full-size",
            connect: ["Không dây (Wireless)", "Bluetooth"],
            led: "RGB",
            priceOld: 7500000,
            discountPercent: 8,
        },
        {
            id: 10,
            name: "Akko 5075S Dracula Castle",
            image: "../../Images/BanPhim/Akko 5075S Dracula Castle.jpg",
            brand: "Akko",
            type: "Cơ",
            switchType: "Akko CS Switch",
            layout: "75%",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 2350000,
            discountPercent: 18,
        },
        {
            id: 11,
            name: "Logitech MX Keys S",
            image: "../../Images/BanPhim/Logitech MX Keys S.jpg",
            brand: "Logitech",
            type: "Văn phòng",
            switchType: "Khác",
            layout: "Full-size",
            connect: ["Không dây (Wireless)", "Bluetooth"],
            led: "Đơn sắc",
            priceOld: 2890000,
            discountPercent: 10,
        },
        {
            id: 12,
            name: "Keychron Q1 Pro",
            image: "../../Images/BanPhim/Keychron Q1 Pro.jpg",
            brand: "Keychron",
            type: "Cơ",
            switchType: "Brown Switch",
            layout: "75%",
            connect: ["Không dây (Wireless)", "Bluetooth"],
            led: "RGB",
            priceOld: 4990000,
            discountPercent: 12,
        },
        {
            id: 13,
            name: "DareU EK87 Queen",
            image: "../../Images/BanPhim/DareU EK87 Queen.jpg",
            brand: "DareU",
            type: "Giả cơ",
            switchType: "Khác",
            layout: "TKL",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 690000,
            discountPercent: 25,
        },
        {
            id: 14,
            name: "Razer Ornata V3",
            image: "../../Images/BanPhim/Razer Ornata V3.webp",
            brand: "Razer",
            type: "Giả cơ",
            switchType: "Razer Mecha-Membrane",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 1990000,
            discountPercent: 20,
        },
        {
            id: 15,
            name: "Fuhlen L411",
            image: "../../Images/BanPhim/Fuhlen L411.jpg",
            brand: "Fuhlen",
            type: "Văn phòng",
            switchType: "Khác",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "Không LED",
            priceOld: 220000,
            discountPercent: 15,
        },
        {
            id: 16,
            name: "Logitech G913 TKL Lightspeed",
            image: "../../Images/BanPhim/Logitech G913 TKL Lightspeed.webp",
            brand: "Logitech",
            type: "Cơ",
            switchType: "GL Tactile",
            layout: "TKL",
            connect: ["Không dây (Wireless)", "Bluetooth"],
            led: "RGB",
            priceOld: 4790000,
            discountPercent: 15,
        },
        {
            id: 17,
            name: "E-Dra EK387",
            image: "../../Images/BanPhim/E-Dra EK387.jpg",
            brand: "E-Dra",
            type: "Cơ",
            switchType: "Blue Switch",
            layout: "TKL",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 950000,
            discountPercent: 22,
        },
        {
            id: 18,
            name: "Apple Magic Keyboard",
            image: "../../Images/BanPhim/Apple Magic Keyboard.webp",
            brand: "Apple",
            type: "Văn phòng",
            switchType: "Khác",
            layout: "75%",
            connect: ["Bluetooth"],
            led: "Không LED",
            priceOld: 2790000,
            discountPercent: 5,
        },
        {
            id: 19,
            name: "Asus ROG Strix Flare II Animate",
            image: "../../Images/BanPhim/Asus ROG Strix Flare II Animate.png",
            brand: "Asus",
            type: "Cơ",
            switchType: "Red Switch",
            layout: "Full-size",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 5490000,
            discountPercent: 10,
        },
        {
            id: 20,
            name: "HyperX Alloy Origins 60",
            image: "../../Images/BanPhim/HyperX Alloy Origins 60.webp",
            brand: "HyperX",
            type: "Cơ",
            switchType: "HyperX Red",
            layout: "60%",
            connect: ["Có dây"],
            led: "RGB",
            priceOld: 2590000,
            discountPercent: 17,
        }
]
const chuot = [
    {
        id: 1,
        name: "Logitech G Pro X Superlight",
        image: "../../Images/Chuot/Logitech G Pro X Superlight.webp",
        brand: "Logitech",
        type: "Gaming",
        connect: ["Không dây (Wireless)"],
        priceOld: 3990000,
        discountPercent: 15,
    },
    {
        id: 2,
        name: "Razer DeathAdder V3 Pro",
        image: "../../Images/Chuot/Razer DeathAdder V3 Pro.webp",
        brand: "Razer",
        type: "Gaming",
        connect: ["Không dây (Wireless)"],
        priceOld: 4190000,
        discountPercent: 10,
    },
    {
        id: 3,
        name: "SteelSeries Rival 3",
        image: "../../Images/Chuot/SteelSeries Rival 3.webp",
        brand: "SteelSeries",
        type: "Gaming",
        connect: ["Có dây"],
        priceOld: 990000,
        discountPercent: 20,
    },
    {
        id: 4,
        name: "Logitech MX Master 3S",
        image: "../../Images/Chuot/Logitech MX Master 3S.png",
        brand: "Logitech",
        type: "Văn phòng",
        connect: ["Bluetooth", "Không dây (Wireless)"],
        priceOld: 2790000,
        discountPercent: 12,
    },
    {
        id: 5,
        name: "Corsair Harpoon RGB Wireless",
        image: "../../Images/Chuot/Corsair Harpoon RGB Wireless.jpg",
        brand: "Corsair",
        type: "Gaming",
        connect: ["Không dây (Wireless)", "Bluetooth"],
        priceOld: 1290000,
        discountPercent: 18,
    },
    {
        id: 6,
        name: "DareU EM908",
        image: "../../Images/Chuot/DareU EM908.webp",
        brand: "DareU",
        type: "Gaming",
        connect: ["Có dây"],
        priceOld: 450000,
        discountPercent: 25,
    },
    {
        id: 7,
        name: "Logitech M331 Silent Plus",
        image: "../../Images/Chuot/Logitech M331 Silent Plus.jpg",
        brand: "Logitech",
        type: "Văn phòng",
        connect: ["Không dây (Wireless)"],
        priceOld: 490000,
        discountPercent: 10,
    },
    {
        id: 8,
        name: "Asus ROG Gladius III",
        image: "../../Images/Chuot/Asus ROG Gladius III.jpg",
        brand: "Asus",
        type: "Gaming",
        connect: ["Có dây"],
        priceOld: 2190000,
        discountPercent: 15,
    },
    {
        id: 9,
        name: "Razer Viper Mini",
        image: "../../Images/Chuot/Razer Viper Mini.webp",
        brand: "Razer",
        type: "Gaming",
        connect: ["Có dây"],
        priceOld: 1190000,
        discountPercent: 22,
    },
    {
        id: 10,
        name: "Logitech Pebble M350",
        image: "../../Images/Chuot/Logitech Pebble M350.jpg",
        brand: "Logitech",
        type: "Văn phòng",
        connect: ["Bluetooth", "Không dây (Wireless)"],
        priceOld: 650000,
        discountPercent: 8,
    },
    {
        id: 11,
        name: "Glorious Model O Wireless",
        image: "../../Images/Chuot/Glorious Model O Wireless.jpg",
        brand: "Glorious",
        type: "Gaming",
        connect: ["Không dây (Wireless)"],
        priceOld: 2490000,
        discountPercent: 10,
    },
    {
        id: 12,
        name: "BenQ Zowie EC2-C",
        image: "../../Images/Chuot/BenQ Zowie EC2-C.webp",
        brand: "BenQ Zowie",
        type: "Gaming",
        connect: ["Có dây"],
        priceOld: 1890000,
        discountPercent: 5,
    },
    {
        id: 13,
        name: "Logitech MX Anywhere 3S",
        image: "../../Images/Chuot/Logitech MX Anywhere 3S.webp",
        brand: "Logitech",
        type: "Văn phòng",
        connect: ["Bluetooth", "Không dây (Wireless)"],
        priceOld: 1990000,
        discountPercent: 15,
    },
    {
        id: 14,
        name: "Razer Basilisk V3",
        image: "../../Images/Chuot/Razer Basilisk V3.webp",
        brand: "Razer",
        type: "Gaming",
        connect: ["Có dây"],
        priceOld: 1790000,
        discountPercent: 20,
    },
    {
        id: 15,
        name: "Apple Magic Mouse",
        image: "../../Images/Chuot/Apple Magic Mouse.webp",
        brand: "Apple",
        type: "Văn phòng",
        connect: ["Bluetooth"],
        priceOld: 2190000,
        discountPercent: 7,
    },
    {
        id: 16,
        name: "SteelSeries Aerox 3 Wireless",
        image: "../../Images/Chuot/SteelSeries Aerox 3 Wireless.webp",
        brand: "SteelSeries",
        type: "Gaming",
        connect: ["Không dây (Wireless)", "Bluetooth"],
        priceOld: 2590000,
        discountPercent: 12,
    },
    {
        id: 17,
        name: "Microsoft Surface Precision Mouse",
        image: "../../Images/Chuot/Microsoft Surface Precision Mouse.jpg",
        brand: "Microsoft",
        type: "Văn phòng",
        connect: ["Bluetooth", "Có dây"],
        priceOld: 2490000,
        discountPercent: 10,
    },
    {
        id: 18,
        name: "Pulsar X2V2 Wireless",
        image: "../../Images/Chuot/Pulsar X2V2 Wireless.webp",
        brand: "Pulsar",
        type: "Gaming",
        connect: ["Không dây (Wireless)"],
        priceOld: 2650000,
        discountPercent: 8,
    },
    {
        id: 19,
        name: "Fuhlen L102",
        image: "../../Images/Chuot/Fuhlen L102.jpg",
        brand: "Fuhlen",
        type: "Văn phòng",
        connect: ["Có dây"],
        priceOld: 250000,
        discountPercent: 30,
    },
    {
        id: 20,
        name: "Corsair Katar Pro XT",
        image: "../../Images/Chuot/Corsair Katar Pro XT.jpg",
        brand: "Corsair",
        type: "Gaming",
        connect: ["Có dây"],
        priceOld: 890000,
        discountPercent: 20,
    },
];
const TaiNghe = [
    {
        id: 1,
        name: "Sony WH-1000XM5",
        image: "../../Images/TaiNghe/Sony WH-1000XM5.png",
        brand: "Sony",
        type: "Chụp tai (Over-ear)",
        connect: ["Bluetooth", "Jack 3.5mm"],
        priceOld: 8990000,
        discountPercent: 10,
    },
    {
        id: 2,
        name: "Apple AirPods Pro 2",
        image: "../../Images/TaiNghe/Apple AirPods Pro 2.webp",
        brand: "Apple",
        type: "Nhét tai (In-ear)",
        connect: ["Bluetooth"],
        priceOld: 6190000,
        discountPercent: 12,
    },
    {
        id: 3,
        name: "Logitech G Pro X Wireless",
        image: "../../Images/TaiNghe/Logitech G Pro X Wireless.jpg",
        brand: "Logitech",
        type: "Gaming",
        connect: ["Wireless"],
        priceOld: 4990000,
        discountPercent: 15,
    },
    {
        id: 4,
        name: "Razer BlackShark V2",
        image: "../../Images/TaiNghe/Razer BlackShark V2.webp",
        brand: "Razer",
        type: "Gaming",
        connect: ["Jack 3.5mm"],
        priceOld: 2790000,
        discountPercent: 20,
    },
    {
        id: 5,
        name: "Corsair HS80 RGB Wireless",
        image: "../../Images/TaiNghe/Corsair HS80 RGB Wireless.jpg",
        brand: "Corsair",
        type: "Gaming",
        connect: ["Wireless"],
        priceOld: 3890000,
        discountPercent: 18,
    },
    {
        id: 6,
        name: "SteelSeries Arctis Nova Pro",
        image: "../../Images/TaiNghe/SteelSeries Arctis Nova Pro.jpg",
        brand: "SteelSeries",
        type: "Gaming",
        connect: ["Wireless", "Bluetooth"],
        priceOld: 8590000,
        discountPercent: 10,
    },
    {
        id: 7,
        name: "Asus ROG Delta S",
        image: "../../Images/TaiNghe/Asus ROG Delta S.png",
        brand: "Asus",
        type: "Gaming",
        connect: ["Jack 3.5mm"],
        priceOld: 4590000,
        discountPercent: 14,
    },
    {
        id: 8,
        name: "Sony WF-1000XM4",
        image: "../../Images/TaiNghe/Sony WF-1000XM4.jpg",
        brand: "Sony",
        type: "Nhét tai (In-ear)",
        connect: ["Bluetooth"],
        priceOld: 5490000,
        discountPercent: 25,
    },
    {
        id: 9,
        name: "Logitech Zone Vibe 100",
        image: "../../Images/TaiNghe/Logitech Zone Vibe 100.png",
        brand: "Logitech",
        type: "Chụp tai (Over-ear)",
        connect: ["Bluetooth"],
        priceOld: 2490000,
        discountPercent: 8,
    },
    {
        id: 10,
        name: "Apple AirPods 3",
        image: "../../Images/TaiNghe/Apple AirPods 3.jpg",
        brand: "Apple",
        type: "Nhét tai (In-ear)",
        connect: ["Bluetooth"],
        priceOld: 4490000,
        discountPercent: 11,
    },
    {
        id: 11,
        name: "Bose QuietComfort Ultra Headphones",
        image: "../../Images/TaiNghe/Bose QuietComfort Ultra Headphones.jpg",
        brand: "Bose",
        type: "Chụp tai (Over-ear)",
        connect: ["Bluetooth", "Jack 3.5mm"],
        priceOld: 11990000,
        discountPercent: 10,
    },
    {
        id: 12,
        name: "Sennheiser Momentum True Wireless 4",
        image: "../../Images/TaiNghe/Sennheiser Momentum True Wireless 4.webp",
        brand: "Sennheiser",
        type: "Nhét tai (In-ear)",
        connect: ["Bluetooth"],
        priceOld: 8490000,
        discountPercent: 8,
    },
    {
        id: 13,
        name: "JBL Tune 760NC",
        image: "../../Images/TaiNghe/JBL Tune 760NC.png",
        brand: "JBL",
        type: "Chụp tai (Over-ear)",
        connect: ["Bluetooth", "Jack 3.5mm"],
        priceOld: 2990000,
        discountPercent: 20,
    },
    {
        id: 14,
        name: "Samsung Galaxy Buds 2 Pro",
        image: "../../Images/TaiNghe/Samsung Galaxy Buds 2 Pro.png",
        brand: "Samsung",
        type: "Nhét tai (In-ear)",
        connect: ["Bluetooth"],
        priceOld: 3990000,
        discountPercent: 15,
    },
    {
        id: 15,
        name: "Audio-Technica ATH-M50xBT2",
        image: "../../Images/TaiNghe/Audio-Technica ATH-M50xBT2.jpg",
        brand: "Audio-Technica",
        type: "Chụp tai (Over-ear)",
        connect: ["Bluetooth", "Jack 3.5mm"],
        priceOld: 5290000,
        discountPercent: 10,
    },
    {
        id: 16,
        name: "HyperX Cloud III Wireless",
        image: "../../Images/TaiNghe/HyperX Cloud III Wireless.webp",
        brand: "HyperX",
        type: "Gaming",
        connect: ["Wireless", "Bluetooth"],
        priceOld: 4190000,
        discountPercent: 12,
    },
    {
        id: 17,
        name: "Anker Soundcore Liberty 4 NC",
        image: "../../Images/TaiNghe/Anker Soundcore Liberty 4 NC.png",
        brand: "Anker",
        type: "Nhét tai (In-ear)",
        connect: ["Bluetooth"],
        priceOld: 2390000,
        discountPercent: 18,
    },
    {
        id: 18,
        name: "Beyerdynamic DT 770 Pro (80 Ohm)",
        image: "../../Images/TaiNghe/Beyerdynamic DT 770 Pro (80 Ohm).webp",
        brand: "Beyerdynamic",
        type: "Chụp tai (Over-ear)",
        connect: ["Jack 3.5mm", "Jack 6.3mm"],
        priceOld: 3990000,
        discountPercent: 5,
    },
    {
        id: 19,
        name: "Xiaomi Redmi Buds 5",
        image: "../../Images/TaiNghe/Xiaomi Redmi Buds 5.webp",
        brand: "Xiaomi",
        type: "Nhét tai (In-ear)",
        connect: ["Bluetooth"],
        priceOld: 990000,
        discountPercent: 22,
    },
    {
        id: 20,
        name: "Razer Kraken V3",
        image: "../../Images/TaiNghe/Razer Kraken V3.webp",
        brand: "Razer",
        type: "Gaming",
        connect: ["Jack 3.5mm"],
        priceOld: 2590000,
        discountPercent: 15,
    }
];
const Webcam = [
    {
        id: 1,
        name: "Logitech C922 Pro Stream",
        image: "../../Images/Webcam/Logitech C922 Pro Stream.webp",
        brand: "Logitech",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro", "Lấy nét tự động"],
        priceOld: 2890000,
        discountPercent: 15,
    },
    {
        id: 2,
        name: "Razer Kiyo Pro",
        image: "../../Images/Webcam/Razer Kiyo Pro.webp",
        brand: "Razer",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro", "Lấy nét tự động", "HDR"],
        priceOld: 4990000,
        discountPercent: 10,
    },
    {
        id: 3,
        name: "Logitech Brio 4K",
        image: "../../Images/Webcam/Logitech Brio 4K.png",
        brand: "Logitech",
        resolution: "4K Ultra HD",
        features: ["Tích hợp micro", "Lấy nét tự động", "Windows Hello"],
        priceOld: 5490000,
        discountPercent: 12,
    },
    {
        id: 4,
        name: "Asus ROG Eye S",
        image: "../../Images/Webcam/Asus ROG Eye S.png",
        brand: "Asus",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro", "Lấy nét tự động"],
        priceOld: 2590000,
        discountPercent: 20,
    },
    {
        id: 5,
        name: "Logitech C270 HD",
        image: "../../Images/Webcam/Logitech C270 HD.webp",
        brand: "Logitech",
        resolution: "HD 720p",
        features: ["Tích hợp micro"],
        priceOld: 790000,
        discountPercent: 25,
    },
    {
        id: 6,
        name: "Logitech StreamCam",
        image: "../../Images/Webcam/Logitech StreamCam.jpg",
        brand: "Logitech",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro", "Lấy nét tự động", "Xoay dọc khung hình"],
        priceOld: 3490000,
        discountPercent: 18,
    },
    {
        id: 7,
        name: "Razer Kiyo",
        image: "../../Images/Webcam/Razer Kiyo.png",
        brand: "Razer",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro", "Lấy nét tự động", "Tích hợp đèn"],
        priceOld: 2490000,
        discountPercent: 14,
    },
    {
        id: 8,
        name: "Logitech C930e",
        image: "../../Images/Webcam/Logitech C930e.png",
        brand: "Logitech",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro", "Lấy nét tự động", "Góc quay rộng"],
        priceOld: 3190000,
        discountPercent: 10,
    },
    // 12 sản phẩm được thêm vào
    {
        id: 9,
        name: "Dell UltraSharp WB7022",
        image: "../../Images/Webcam/Dell UltraSharp WB7022.webp",
        brand: "Dell",
        resolution: "4K Ultra HD",
        features: ["Tích hợp micro", "Lấy nét tự động", "HDR"],
        priceOld: 5990000,
        discountPercent: 10,
    },
    {
        id: 10,
        name: "AnkerWork B600 Video Bar",
        image: "../../Images/Webcam/AnkerWork B600 Video Bar.webp",
        brand: "Anker",
        resolution: "2K QHD",
        features: ["Tích hợp micro", "Lấy nét tự động", "Tích hợp đèn"],
        priceOld: 4490000,
        discountPercent: 15,
    },
    {
        id: 11,
        name: "Elgato Facecam",
        image: "../../Images/Webcam/Elgato Facecam.webp",
        brand: "Elgato",
        resolution: "Full HD 1080p",
        features: ["Lấy nét cố định (Fixed Focus)"],
        priceOld: 3990000,
        discountPercent: 12,
    },
    {
        id: 12,
        name: "Creative Live! Cam Sync 1080p V2",
        image: "../../Images/Webcam/Creative Live! Cam Sync 1080p V2.jpg",
        brand: "Creative",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro kép", "Nắp che ống kính"],
        priceOld: 1290000,
        discountPercent: 20,
    },
    {
        id: 13,
        name: "Logitech C505 HD",
        image: "../../Images/Webcam/Logitech C505 HD.webp",
        brand: "Logitech",
        resolution: "HD 720p",
        features: ["Tích hợp micro tầm xa"],
        priceOld: 1190000,
        discountPercent: 18,
    },
    {
        id: 14,
        name: "Xiaomi Imilab W88S",
        image: "../../Images/Webcam/Xiaomi Imilab W88S.png",
        brand: "Xiaomi",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro", "Chân đế đa năng"],
        priceOld: 590000,
        discountPercent: 30,
    },
    {
        id: 15,
        name: "Corsair Facecam",
        image: "../../Images/Webcam/Corsair Facecam.webp",
        brand: "Corsair",
        resolution: "Full HD 1080p",
        features: ["Cảm biến Sony", "Lấy nét cố định (Fixed Focus)"],
        priceOld: 3890000,
        discountPercent: 10,
    },
    {
        id: 16,
        name: "Anker PowerConf C200",
        image: "../../Images/Webcam/Anker PowerConf C200.webp",
        brand: "Anker",
        resolution: "2K QHD",
        features: ["Tích hợp micro", "Lấy nét tự động", "Nắp che ống kính"],
        priceOld: 1750000,
        discountPercent: 15,
    },
    {
        id: 17,
        name: "Asus Webcam C3",
        image: "../../Images/Webcam/Asus Webcam C3.jpg",
        brand: "Asus",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro", "Xoay 360 độ"],
        priceOld: 1490000,
        discountPercent: 22,
    },
    {
        id: 18,
        name: "Poly Studio P5",
        image: "../../Images/Webcam/Poly Studio P5.jpg",
        brand: "Poly",
        resolution: "Full HD 1080p",
        features: ["Tích hợp micro", "Lấy nét tự động", "Nắp che ống kính"],
        priceOld: 2990000,
        discountPercent: 10,
    },
    {
        id: 19,
        name: "Razer Kiyo X",
        image: "../../Images/Webcam/Razer Kiyo X.jpg",
        brand: "Razer",
        resolution: "Full HD 1080p",
        features: ["Lấy nét tự động", "Tùy chỉnh cài đặt"],
        priceOld: 1990000,
        discountPercent: 15,
    },
    {
        id: 20,
        name: "Logitech C310 HD",
        image: "../../Images/Webcam/Logitech C310 HD.png",
        brand: "Logitech",
        resolution: "HD 720p",
        features: ["Tích hợp micro", "Công nghệ RightLight 2"],
        priceOld: 990000,
        discountPercent: 20,
    }
];